PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.ModelBinding;

namespace PartsUnlimited.Models
{
    //[Bind(Include = "FirstName,LastName,Address,City,State,PostalCode,Country,Phone,Email")]
    public class Order
    {
        [BindNever]
        [ScaffoldColumn(false)]
        public int OrderId { get; set; }

        [BindNever]
        [ScaffoldColumn(false)]
        public System.DateTime OrderDate { get; set; }

        [BindNever]
        [Required]
        [ScaffoldColumn(false)]
        public string Username { get; set; }

        [Required]
        [Display(Name = "Name")]
        [StringLength(160)]
        public string Name { get; set; }

        [Required]
        [StringLength(70, MinimumLength = 3)]
        public string Address { get; set; }

        [Required]
        [StringLength(40)]
        public string City { get; set; }

        [Required]
        [StringLength(40)]
        public string State { get; set; }

        [Required]
        [Display(Name = "Postal Code")]
        [StringLength(10, MinimumLength = 5)]
        public string PostalCode { get; set; }

        [Required]
        [StringLength(40)]
        public string Country { get; set; }

        [Required]
        [StringLength(24)]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "Email Address")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",
            ErrorMessage = "Email is is not valid.")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [BindNever]
        [ScaffoldColumn(false)]
        public decimal Total { get; set; }

        [BindNever]
        public List<OrderDetail> OrderDetails { get; set; }
    }
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Models/OrderCostSummary.cs
namespace PartsUnlimited.Models
{
    public class OrderCostSummary
    {
        public string CartSubTotal { get; set; }
        public string CartShipping { get; set; }
        public string CartTax { get; set; }
        public string CartTotal { get; set; }
    }
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Areas/Admin/Controllers/OrdersController.cs
using PartsUnlimited.Utils;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PartsUnlimited.Models;
using PartsUnlimited.ViewModels;

namespace PartsUnlimited.Areas.Admin.Controllers
{
    public class OrdersController : AdminController
    {
        private readonly IOrdersQuery _ordersQuery;

        public OrdersController(IOrdersQuery ordersQuery)
        {
            _ordersQuery = ordersQuery;
        }

        public async Task<ActionResult> Index(string username, DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            return View(await _ordersQuery.IndexHelperAsync(username, start, end, invalidOrderSearch, true));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", new { invalidOrderSearch = Request.QueryString["id"] });
            }

            var order = await _ordersQuery.FindOrderAsync(id.Value);

            if (order == null)
            {
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }

            var itemsCount = order.OrderDetails.Sum(x => x.Count);
            var subTotal = order.OrderDetails.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var costSummary = new OrderCostSummary
            {
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C")
            };

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Controllers/OrdersController.cs
using PartsUnlimited.Utils;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PartsUnlimited.Models;
using PartsUnlimited.ViewModels;

namespace PartsUnlimited.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrdersQuery _ordersQuery;
        private readonly ITelemetryProvider _telemetry;
		private readonly IShippingTaxCalculator _shippingTaxCalc;

		public OrdersController(IOrdersQuery ordersQuery, ITelemetryProvider telemetryProvider,
			IShippingTaxCalculator shippingTaxCalc)
        {
            _ordersQuery = ordersQuery;
            _telemetry = telemetryProvider;
			_shippingTaxCalc = shippingTaxCalc;
        }

        public async Task<ActionResult> Index(DateTime? start, DateTime? end, string invalidOrderSearch)
        {
            var username = User.Identity.GetUserName();

            return View(await _ordersQuery.IndexHelperAsync(username, start, end, invalidOrderSearch, false));
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                _telemetry.TrackTrace("Order/Server/NullId");
                return RedirectToAction("Index", new { invalidOrderSearch = Request.QueryString["id"] });
            }

            var order = await _ordersQuery.FindOrderAsync(id.Value);
            var username = User.Identity.GetUserName();

            // If the username isn't the same as the logged in user, return as if the order does not exist
            if (order == null || !String.Equals(order.Username, username, StringComparison.Ordinal))
            {
                _telemetry.TrackTrace("Order/Server/UsernameMismatch");
                return RedirectToAction("Index", new { invalidOrderSearch = id.ToString() });
            }

            // Capture order review event for analysis
            var eventProperties = new Dictionary<string, string>()
                {
                    {"Id", id.ToString() },
                    {"Username", username }
                };
            var costSummary = new OrderCostSummary()
            {
                CartSubTotal = 0.ToString("C"),
                CartShipping = 0.ToString("C"),
                CartTax = 0.ToString("C"),
                CartTotal = 0.ToString("C"),
            };
            if (order.OrderDetails == null)
            {
                _telemetry.TrackEvent("Order/Server/NullDetails", eventProperties, null);
            }
            else
            {
                var eventMeasurements = new Dictionary<string, double>()
                {
                    {"LineItemCount", order.OrderDetails.Count }
                };
                _telemetry.TrackEvent("Order/Server/Details", eventProperties, eventMeasurements);

				costSummary = _shippingTaxCalc.CalculateCost(order.OrderDetails, order.PostalCode);
				//var itemsCount = order.OrderDetails.Sum(x => x.Count);
				//var subTotal = order.OrderDetails.Sum(x => x.Count * x.Product.Price);
				//var shipping = itemsCount * (decimal)6.00;
				//var tax = (subTotal + shipping) * (decimal)0.06;
				//var total = subTotal + shipping + tax;

				//costSummary.CartSubTotal = subTotal.ToString("C");
				//costSummary.CartShipping = shipping.ToString("C");
				//costSummary.CartTax = tax.ToString("C");
				//costSummary.CartTotal = total.ToString("C");
			}

            var viewModel = new OrderDetailsViewModel
            {
                OrderCostSummary = costSummary,
                Order = order
            };

            return View(viewModel);
        }
    }
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Controllers/RecommendationsController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PartsUnlimited.Models;
using PartsUnlimited.Recommendations;
using PartsUnlimited.Utils;

namespace PartsUnlimited.Controllers
{
    public class RecommendationsController : Controller
    {
        private readonly IPartsUnlimitedContext db;
        private readonly IRecommendationEngine recommendation;

        public RecommendationsController(IPartsUnlimitedContext context, IRecommendationEngine recommendationEngine)
        {
            db = context;
            recommendation = recommendationEngine;
        }

        public async Task<ActionResult> GetRecommendations(string productId)
        {
            if (!ConfigurationHelpers.GetBool("ShowRecommendations"))
            {
                return new EmptyResult();
            }

            var recommendedProductIds = await recommendation.GetRecommendationsAsync(productId);

            var recommendedProducts = await db.Products.Where(x => recommendedProductIds.Contains(x.ProductId.ToString())).ToListAsync();

            return PartialView("_Recommendations", recommendedProducts);
        }
    }
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Controllers/StoreController.cs
using PartsUnlimited.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Mvc;
using PartsUnlimited.Utils;
using PartsUnlimited.ViewModels;

namespace PartsUnlimited.Controllers
{
    public class StoreController : Controller
    {
        private readonly IPartsUnlimitedContext db;

        public StoreController(IPartsUnlimitedContext context)
        {
            db = context;
        }

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var genres = db.Categories.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(int categoryId)
        {
            // Retrieve Category genre and its Associated associated Products products from database
            var genreModel = db.Categories.Include("Products").Single(g => g.CategoryId == categoryId);

            return View(genreModel);
        }

        public ActionResult Details(int id)
        {

            var productCacheKey = string.Format("product_{0}", id);
            var product = MemoryCache.Default[productCacheKey] as Product;
            if (product == null)
            {
                product = db.Products.Single(a => a.ProductId == id);
                //Remove it from cache if not retrieved in last 10 minutes
                MemoryCache.Default.Add(productCacheKey, product, new CacheItemPolicy { SlidingExpiration = TimeSpan.FromMinutes(10) });
            }
            var viewModel = new ProductViewModel
            {
                Product = product,
                ShowRecommendations = ConfigurationHelpers.GetBool("ShowRecommendations")
            };

            return View(viewModel);
        }

    }
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/DemoLinkDisplay.cshtml
@{
    ViewBag.Title = "Demo link display page - Not for production use";
}

<section>
    <h2>@ViewBag.Title</h2>
    <div class="row">
        <div class="col-md-6">
            <div>
                <p>
                    Demo link display page - Not for production use.
                </p>

                @if (ViewBag.Link != null)
                {
                    <p class="text-danger">
                        For DEMO only: You can click this link to confirm the email: [[<a href="@ViewBag.Link">link</a>]]
                        <br />
                        Please change this code to register an email service in IdentityConfig to send an email.
                    </p>
                }
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
</section>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_AdminMenu.cshtml
@using PartsUnlimited.Areas.Admin

@{
    var claims = User.Identity as System.Security.Claims.ClaimsIdentity;
    var isAdmin = claims.HasClaim(AdminConstants.ManageStore.Name, AdminConstants.ManageStore.Allowed);
}

@if (isAdmin)
{
    <li class="dropdown">
        <a href="@Url.Action("Index", "Store")" id="admin-link" class="dropdown-toggle head-link" data-toggle="dropdown">Admin&nbsp;<br class="hidden-xs" /><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li> @Html.ActionLink("Manage Items", "Index", "StoreManager", new { area = AdminConstants.Area }, null) </li>
            <li> @Html.ActionLink("View Orders", "Index", "Orders", new { area = AdminConstants.Area }, null) </li>
            <li> @Html.ActionLink("Find Customers", "Find", "Customer", new { area = AdminConstants.Area }, null) </li>
            <li> @Html.ActionLink("View Rainchecks", "Index", "Raincheck", new { area = AdminConstants.Area }, null) </li>
        </ul>
    </li>
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_Announcement.cshtml
@model PartsUnlimited.Models.Product

<div class="alert alert-new-arrival @if (Model == null) { <text>hidden</text>}" id="alert-new-arrival" role="alert">
    <div class="container">
        <div class="alert-content">
            <span class="glyphicon glyphicon-bullhorn"></span>
            @if (Model == null)
            {
                <a id="new-arrival" href="#"></a>
            }
            else
            {
                <a id="new-arrival" href="@Url.Action("Details", "Store", new { Area = string.Empty, id = Model.ProductId })">@string.Format(" New Arrival : {0}", Model.Title)</a>
            }
        </div>
    </div>
</div>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_CartSummary.cshtml
<li>
    <a href="@Url.Action("Index", "ShoppingCart")" title="@ViewBag.CartSummary" class="head-link" id="shopping-cart-link">

        <div>Cart</div>
        @if (ViewBag.CartCount > 0)
        {
            <span class="hidden-xs" id="cart-count">@ViewBag.CartCount</span>
        }
    </a>
</li>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_CategoryMenu.cshtml
@model IEnumerable<PartsUnlimited.Models.Category>
@foreach (var genre in Model)
{
    <li>@Html.ActionLink(genre.Name, "Browse", "Store", new { CategoryId = genre.CategoryId, Area = string.Empty }, null)</li>
}
<li>@Html.ActionLink("More", "Index", "Store", new {Area = string.Empty }, null)</li>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_Layout.cshtml
@using PartsUnlimited.Models
@using PartsUnlimited.Utils
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Parts Unlimited</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/signalr")*@
    @*<script src="/signalr/hubs"></script>*@
    @Scripts.Render("~/bundles/site")

    <!-- AppInsights -->
    <script type="text/javascript">
  var appInsights=window.appInsights||function(config){
    function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
    }({
        instrumentationKey:"@System.Web.Configuration.WebConfigurationManager.AppSettings.Get("Keys:ApplicationInsights:InstrumentationKey")"
    });

    window.appInsights=appInsights;
    appInsights.trackPageView();
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="primary-menu">
                    <div class="pull-left logo">
                        <a class="block logo-image" href="@Url.Action("Index", "Home", new { Area = string.Empty })">
                            <img src="/Images/unlimited_logo.png" alt="Parts Unlimited logo" />
                        </a>
                        <a class="block" href="@Url.Action("Index", "Home", new { Area = string.Empty })">
                            <h1>Parts Unlimited</h1>
                            <h2>a Fabrikam subsidiary</h2>
                        </a>

                        <div class="visible-xs cart">
                            <a href="@Url.Action("Index", "ShoppingCart", new { Area = string.Empty })" class="head-link" id="shopping-cart-link"></a>
                        </div>
                    </div>
                    <div class="pull-right navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-header-nav">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="collapse-header-nav">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="hidden-xs">
                                    <div id="search-link-box">
                                        @using (Html.BeginForm("Index", "Search", new { Area = string.Empty }, FormMethod.Get))
                                        {
                                            @Html.TextBox("q", null, new { @class = "form-control", id = "search-box", placeholder = "Keyword" })
                                            <input type="submit" id="search-link" value="Search" />
                                        }
                                    </div>
                                </li>
                                <li><a href="@Url.Action("Index", "Home", new { Area = string.Empty })" class="head-link" id="home-link">Home</a></li>
                                @Html.Partial("_CartSummary", (IEnumerable<string>)ViewBag.CartSummary)
                                @Html.Partial("_AdminMenu")
                                @Html.Partial("_Login")
                                <li class="dropdown visible-xs">
                                    <a href="@Url.Action("Index", "Store", new { Area = string.Empty })" class="dropdown-toggle head-link" data-toggle="dropdown">Categories&nbsp;<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        @Html.Partial("_CategoryMenu", (IEnumerable<Category>)ViewBag.Categories)
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="category-menu">
                <div class="container">
                    <div class="hidden-xs">
                        <ul>
                            @Html.Partial("_CategoryMenu", (IEnumerable<Category>)ViewBag.Categories)
                        </ul>
                    </div>
                </div>
            </div>
            @Html.Partial("_Announcement", (Product)ViewBag.Product)
        </nav>
        <div class="visible-xs search-box">
            @using (Html.BeginForm("Index", "Search", new { Area = string.Empty }, FormMethod.Get))
            {
                @Html.TextBox("q", null, new { @class = "form-control", placeholder = "Search" })
                <input type="submit" value="" />
            }
        </div>
    </header>

    @RenderSection("prebody", false)
    <div class="container">
        @RenderBody()
    </div>
    <div class="clearfix"></div>

    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="row">
                    <div class="col-md-3">
                        <h4>Site Menu</h4>
                        <ul>
                            <li><a href="@Url.Action("Index", "Home", new { Area = string.Empty }, null)">Home</a></li>
                            <li><a href="@Url.Action("Index", "Store", new { Area = string.Empty }, null)">Browse</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Account</h4>
                        <ul>
                            <li>@Html.ActionLink("Manage Account", "Index", "Manage", new { Area = string.Empty }, htmlAttributes: new { title = "Manage" })</li>
                            <li>@Html.ActionLink("Shopping Cart", "Index", "ShoppingCart", new { Area = string.Empty }, null)</li>
                            <li>@Html.ActionLink("View Orders", "Index", "Orders", new { Area = string.Empty }, null)</li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Additional Info</h4>
                        <ul>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Terms and Conditions</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>Develop</h4>
                        <ul>
                            <li><a>GitHub Source</a></li>
                            <li><a>License Agreement</a></li>
                            <li><a href="http://asp.net/" target="_blank">ASP.NET</a></li>
                        </ul>
                        <p>Deploy to Azure</p>
                        <a class="deploy-azure">
                            @Html.Image("deploy_button.png", "deploy to azure image")
                        </a>
                    </div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-6">
                        <div class="pull-left-sm">
                            © @DateTime.UtcNow.Year Microsoft. Based on The Phoenix Project by <a href="http://www.realgenekim.me/" class="footer-link">Gene Kim</a>.
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-left-sm pull-right-md">
                            All rights reserved. Your payments are safe and secure.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/respond")
    @RenderSection("scripts", required: false)
</body>
</html>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_Login.cshtml
@if (User.Identity.IsAuthenticated)
{
    var isNtlm = User.Identity.AuthenticationType == "NTLM";
    
    <li class="dropdown">
        <a href="@Url.Action("Index", "Store")" id="profile-link" class="dropdown-toggle head-link" data-toggle="dropdown">Profile&nbsp;<br class="hidden-xs" /><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("Manage Account", "Index", "Manage", new { Area = string.Empty }, htmlAttributes: new { title = "Manage" })</li>
            <li>@Html.ActionLink("View Orders", "Index", "Orders", new { Area = string.Empty }, null)</li>
            @if (!isNtlm)
            {
            <li>
                @*Either NTLM will be used or social authentication will be used. Based on the authentication schemes enabled remove an unused block.*@
                @using (Html.BeginForm("LogOff", "Account", new { Area = string.Empty }, FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                }
                <a href="javascript:document.getElementById('logoutForm').submit()" >Log off</a>
            </li>
            }
        </ul>
    </li>
}
else
{
    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "login-link", @class = "head-link" })</li>
}

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_OrdersSearch.cshtml
@model PartsUnlimited.ViewModels.OrdersModel

<div id="order-history-page">
    <section>
        <h2>Order History</h2>

        <div class="row">
            <div class="col-md-6 col-border-md-right">
                <h4>Search By Date</h4>

                @using (Html.BeginForm("Index", "Orders", FormMethod.Get))
                {
                    if (Model.IsAdminSearch)
                    {
                        <div class="row form-group">
                            <div class="col-xs-12 col-sm-12 col-md-3 text-right-md">
                                <label for="inputfield1" class="control-label">Username</label>
                            </div>
                            <div class="col-xs-12 col-sm-8 col-md-7">
                                <input type="text" class="form-control" name="username" value="@Model.Username" placeholder="Username"  />
                            </div>
                        </div>
                    }

                    <div class="row form-group">
                        <div class="col-xs-12 col-sm-12 col-md-3 text-right-md">
                            <label for="inputfield1" class="control-label">Start date</label>
                        </div>
                        <div class="col-xs-12 col-sm-8 col-md-7">
                            <input type="text" class="form-control jquery-ui-datepicker" name="start" value="@Model.StartDate.ToString("d")" />
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-xs-12 col-sm-12 col-md-3 text-right-md">
                            <label for="inputfield1" class="control-label">End date</label>
                        </div>
                        <div class="col-xs-12 col-sm-8 col-md-7">
                            <input type="text" class="form-control jquery-ui-datepicker" name="end" value="@Model.EndDate.ToString("d")" />
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-8 col-md-10">
                            <input type="submit" class="btn" value="Search" />
                        </div>
                    </div>
                }
            </div>
            <div class="col-md-6 wide-col-padding">
                <h4>Search By Order Number</h4>

                <div class="row form-group">
                    @using (Html.BeginForm("Details", "Orders", FormMethod.Get))
            {
                        <div class="col-sm-8 col-md-10">
                            <input type="text" class="form-control" id="name" name="id" placeholder="Order number" />
                            <input class="btn" type="submit" value="Open" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

    <section class="section-alt">
        @if (Model.Orders.Any())
        {

            foreach (var order in Model.Orders)
            {
                <div class="row border order">
                    <div class="col-xs-12 col-sm-3 order-summary">
                        <div>Order Number: #@order.OrderId</div>
                        <div>Order Date: @order.OrderDate.ToString("d")</div>
                        <div><a href="@Url.Action("Details", "Orders", new { id = order.OrderId })" class="action-link">View order details</a></div>
                    </div>
                    <div class="col-xs-12 col-sm-9 order-detail">
                        <div class="row">
                            @foreach (var orderDetail in order.OrderDetails)
                            {
                                <div class="col-xs-12 order-detail-item">
                                    <h4><strong>@orderDetail.Count x @orderDetail.Product.Title</strong></h4>
                                    <p>@orderDetail.UnitPrice</p>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="alert alert-warning">
                No orders were found matching the criteria.
            </div>
        }
    </section>
</div>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_ProductList.cshtml
@model IEnumerable<PartsUnlimited.Models.Product>
<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            <div class="list-item-part">
                <a href="@Url.Action("Details", "Store", new { id = product.ProductId })" title="@product.Title">
                
                    <div class="product-image-container hover-over hidden-xs">
                        <div class="image">
                            <img src="/images/@product.ProductArtUrl" alt="@product.Title" />
                        </div>
                        <div class="detail">
                            <h4>@product.Title</h4>
                            <h5>@product.Price.ToString("C")</h5>
                        </div>
                        <div class="mouse-over hidden-xs">
                            <div class="image-second">
                                <img src="/images/@product.ProductArtUrl" alt="@product.Title zoom" />
                            </div>

                            <div class="shop-now">
                                <span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;<span>Shop Now</span>
                            </div>
                        </div>
                    </div>

                    <div class="row visible-xs">
                        <div class="col-xs-4 col-sm-12 col-md-12 no-gutter-sm no-gutter image">
                            <img src="/images/@product.ProductArtUrl" alt="@product.Title" />
                        </div>
                        <div class="col-xs-8 col-sm-12 col-md-12 detail">
                            <h4>@product.Title</h4>
                            <h5>@product.Price.ToString("C")</h5>
                        </div>
                    </div>

                </a>
            </div>
        </div>
    }
</div>

PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/Shared/_Recommendations.cshtml
@model IEnumerable<PartsUnlimited.Models.Product>

@if (Model.Any())
{
    <h2>You may also consider</h2>
    @Html.Partial("_ProductList", Model)
}